package com.narmada.measure.utils

import android.util.Log

object GujaratiUtil {

    // Gujarati unicode size - \u0A81 to \u0AD0
    // Gujarati digit unicode size - \u0AE6 to \u0AEF

    fun gujToShreeGuj(text: String): Pair<Boolean, String> {

        val allUnicodeList = gujaratiCharacters.keys.toList()
        val newString = StringBuilder()

        var isSuccess = true

        text.toCharArray().iterator()
            .forEach { c: Char ->

                if(c.isWhitespace()) {
                    newString.append(' ')
                } else if(allUnicodeList.contains(c.toString())) {
                    newString.append(shreeGujCharacters[gujaratiCharacters[c.toString()]])
                    Log.d("TAG", "gujToShreeGuj: '${c}'")
                } else {
                    Log.d("TAG", "gujToShreeGuj: '${c}' not allowed!")
                    isSuccess = false
                }
            }

        return Pair(isSuccess, newString.toString())
    }

    private val gujaratiCharacters = hashMapOf(
        "ઁ" to "\u0a81",
        "ં" to "\u0a82",
        "ઃ" to "\u0a83",
        "અ" to "\u0a85",
        "આ" to "\u0a86",
        "ઇ" to "\u0a87",
        "ઈ" to "\u0a88",
        "ઉ" to "\u0a89",
        "ઊ" to "\u0a8a",
        "ઋ" to "\u0a8b",
        "ઌ" to "\u0a8c",
        "ઍ" to "\u0a8d",
        "એ" to "\u0a8f",
        "ઐ" to "\u0a90",
        "ઑ" to "\u0a91",
        "ઓ" to "\u0a93",
        "ઔ" to "\u0a94",
        "ક" to "\u0a95",
        "ખ" to "\u0a96",
        "ગ" to "\u0a97",
        "ઘ" to "\u0a98",
        "ઙ" to "\u0a99",
        "ચ" to "\u0a9a",
        "છ" to "\u0a9b",
        "જ" to "\u0a9c",
        "ઝ" to "\u0a9d",
        "ઞ" to "\u0a9e",
        "ટ" to "\u0a9f",
        "ઠ" to "\u0aa0",
        "ડ" to "\u0aa1",
        "ઢ" to "\u0aa2",
        "ણ" to "\u0aa3",
        "ત" to "\u0aa4",
        "થ" to "\u0aa5",
        "દ" to "\u0aa6",
        "ધ" to "\u0aa7",
        "ન" to "\u0aa8",
        "પ" to "\u0aaa",
        "ફ" to "\u0aab",
        "બ" to "\u0aac",
        "ભ" to "\u0aad",
        "મ" to "\u0aae",
        "ય" to "\u0aaf",
        "ર" to "\u0ab0",
        "લ" to "\u0ab2",
        "ળ" to "\u0ab3",
        "વ" to "\u0ab5",
        "શ" to "\u0ab6",
        "ષ" to "\u0ab7",
        "સ" to "\u0ab8",
        "હ" to "\u0ab9",
        "઼" to "\u0abc",
        "ઽ" to "\u0abd",
        "ા" to "\u0abe",
        "િ" to "\u0abf",
        "ી" to "\u0ac0",
        "ુ" to "\u0ac1",
        "ૂ" to "\u0ac2",
        "ૃ" to "\u0ac3",
        "ૄ" to "\u0ac4",
        "ૅ" to "\u0ac5",
        "ે" to "\u0ac7",
        "ૈ" to "\u0ac8",
        "ૉ" to "\u0ac9",
        "ો" to "\u0acb",
        "ૌ" to "\u0acc",
        "્" to "\u0acd",
        "ૐ" to "\u0ad0",
        "ૠ" to "\u0ae0",
        "ૡ" to "\u0ae1",
        "ૣ" to "\u0ae2",
        "ૣ" to "\u0ae3",
        "૦" to "\u0ae6",
        "૧" to "\u0ae7",
        "૨" to "\u0ae8",
        "૩" to "\u0ae9",
        "૪" to "\u0aea",
        "૫" to "\u0aeb",
        "૬" to "\u0aec",
        "૭" to "\u0aed",
        "૮" to "\u0aee",
        "૯" to "\u0aef",
        "૰" to "\u0af0",
        "૱" to "\u0af1",
        "ૹ" to "\u0af9",
        "ૺ" to "\u0afa",
        "ૻ" to "\u0afb",
        "ૼ" to "\u0afc",
        "૽" to "\u0afd",
        "૾" to "\u0afe",
        "૿" to "\u0aff",
    )

    private val shreeGujCharacters = hashMapOf(
        "\u0a81" to "ƒ",
        "\u0a82" to "„",
        "\u0a83" to ":",
        "\u0a85" to "A",
        "\u0a86" to "Ap",
        "\u0a87" to "B",
        "\u0a88" to "C",
        "\u0a89" to "D",
        "\u0a8a" to "E",
        "\u0a8b" to "F",
        "\u0a8c" to "ઌ",
        "\u0a8d" to "A¸",
        "\u0a8f" to "A¡",
        "\u0a90" to "A¥",
        "\u0a91" to "Ap¸",
        "\u0a93" to "Ap¡",
        "\u0a94" to "Ap¥",
        "\u0a95" to "L",
        "\u0a96" to "M",
        "\u0a97" to "N",
        "\u0a98" to "O",
        "\u0a99" to "P",
        "\u0a9a" to "Q",
        "\u0a9b" to "R",
        "\u0a9c" to "S",
        "\u0a9d" to "T",
        "\u0a9e" to "U",
        "\u0a9f" to "V",
        "\u0aa0" to "W",
        "\u0aa1" to "X",
        "\u0aa2" to "Y",
        "\u0aa3" to "Z",
        "\u0aa4" to "s",
        "\u0aa5" to "\\",
        "\u0aa6" to "v",
        "\u0aa7" to "^",
        "\u0aa8" to "_",
        "\u0aaa" to "`",
        "\u0aab" to "a",
        "\u0aac" to "b",
        "\u0aad" to "c",
        "\u0aae" to "d",
        "\u0aaf" to "e",
        "\u0ab0" to "f",
        "\u0ab2" to "g",
        "\u0ab3" to "m",
        "\u0ab5" to "h",
        "\u0ab6" to "i",
        "\u0ab7" to "j",
        "\u0ab8" to "k",
        "\u0ab9" to "l",
        "\u0abc" to "઼",
        "\u0abd" to "@",
        "\u0abe" to "p",
        "\u0abf" to "r",
        "\u0ac0" to "u",
        "\u0ac1" to "y",
        "\u0ac2" to "|",
        "\u0ac3" to "©",
        "\u0ac4" to "«",
        "\u0ac5" to "¸",
        "\u0ac7" to "¡",
        "\u0ac8" to "¥",
        "\u0ac9" to "p¸",
        "\u0acb" to "p¡",
        "\u0acc" to "p¥",
        "\u0acd" to "¹",
        "\u0ad0" to "±",
        "\u0ae0" to "G",
        "\u0ae1" to "ૡ",
        "\u0ae2" to "ૣ",
        "\u0ae3" to "ૣ",
        "\u0ae6" to "0",
        "\u0ae7" to "1",
        "\u0ae8" to "2",
        "\u0ae9" to "3",
        "\u0aea" to "4",
        "\u0aeb" to "5",
        "\u0aec" to "6",
        "\u0aed" to "7",
        "\u0aee" to "8",
        "\u0aef" to "9",
        "\u0af0" to "૰",
        "\u0af1" to "૱",
        "\u0af9" to "ૹ",
        "\u0afa" to "ૺ",
        "\u0afb" to "ૻ",
        "\u0afc" to "ૼ",
        "\u0afd" to "૽",
        "\u0afe" to "૾",
        "\u0aff" to "૿",
    )

}